export const StateCircles = [
    {
        "title": "Jammu and Kashmir",
        "transform": "translate(133,70)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Jammu and Kashmir",
        "text": "Jammu and Kashmir",
        "id": "5f48ce592a9bb065cdf9fb2b"
    },
    {
        "title": "Himachal Pradesh",
        "transform": "translate(190,115)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Himachal Pradesh",
        "text": "Himachal Pradesh",
        "id": "5f48ce592a9bb065cdf9fb2a"
    },
    {
        "title": "Uttarakhand",
        "transform": "translate(235,150)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Uttarakhand",
        "text": "Uttarakhand",
        "id": "5f48ce592a9bb065cdf9fb3e"
    },
    {
        "title": "Punjab",
        "transform": "translate(150,135)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Punjab",
        "text": "Punjab",
        "id": "5f48ce592a9bb065cdf9fb38"
    },
    {
        "title": "Haryana",
        "transform": "translate(170,165)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Haryana",
        "text": "Haryana",
        "id": "5f48ce592a9bb065cdf9fb29"
    },
    {
        "title": "Uttar Pradesh",
        "transform": "translate(250,210)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Uttar Pradesh",
        "text": "Uttar Pradesh",
        "id": "5f48ce592a9bb065cdf9fb3f"
    },
    {
        "title": "Rajasthan",
        "transform": "translate(100,240)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Rajasthan",
        "text": "Rajasthan",
        "id": "5f48ce592a9bb065cdf9fb39"
    },
    {
        "title": "Madhya Pradesh",
        "transform": "translate(200,300)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Madhya Pradesh",
        "text": "Madhya Pradesh",
        "id": "5f48ce592a9bb065cdf9fb30"
    },
    {
        "title": "Gujarat",
        "transform": "translate(70,305)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Gujarat",
        "text": "Gujarat",
        "id": "5f48ce592a9bb065cdf9fb28"
    },
    {
        "title": "Maharashtra",
        "transform": "translate(160,370)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Maharashtra",
        "text": "Maharashtra",
        "id": "5f48ce592a9bb065cdf9fb31"
    },
    {
        "title": "Karnataka",
        "transform": "translate(155,475)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Karnataka",
        "text": "Karnataka",
        "id": "5f48ce592a9bb065cdf9fb2d"
    },
    {
        "title": "Tamil Nadu",
        "transform": "translate(210,570)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Tamil Nadu",
        "text": "Tamil Nadu",
        "id": "5f48ce592a9bb065cdf9fb3b"
    },
    {
        "title": "Kerala",
        "transform": "translate(160,570)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Kerala",
        "text": "Kerala",
        "id": "5f48ce592a9bb065cdf9fb2e"
    },
    {
        "title": "Andhra Pradesh",
        "transform": "translate(215,485)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Andhra Pradesh",
        "text": "Andhra Pradesh",
        "id": "5f48ce592a9bb065cdf9fb20"
    },
    {
        "title": "Chhattisgarh",
        "transform": "translate(280,335)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Chhattisgarh",
        "text": "Chhattisgarh",
        "id": "5f48ce592a9bb065cdf9fb25"
    },
    {
        "title": "Bihar",
        "transform": "translate(370,245)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Bihar",
        "text": "Bihar",
        "id": "5f48ce592a9bb065cdf9fb23"
    },
    {
        "title": "Odisha",
        "transform": "translate(340,355)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Odisha",
        "text": "Odisha",
        "id": "5f48ce592a9bb065cdf9fb36"
    },
    {
        "title": "Jharkhand",
        "transform": "translate(360,300)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Jharkhand",
        "text": "Jharkhand",
        "id": "5f48ce592a9bb065cdf9fb2c"
    },
    {
        "title": "West Bengal",
        "transform": "translate(410,300)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "West Bengal",
        "text": "West Bengal",
        "id": "5f48ce592a9bb065cdf9fb40"
    },
    {
        "title": "Sikkim",
        "transform": "translate(430,210)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Sikkim",
        "text": "Sikkim",
        "id": "5f48ce592a9bb065cdf9fb3a"
    },
    {
        "title": "Assam",
        "transform": "translate(530,240)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Assam",
        "text": "Assam",
        "id": "5f48ce592a9bb065cdf9fb22"
    },
    {
        "title": "Meghalaya",
        "transform": "translate(495,250)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Meghalaya",
        "text": "Meghalaya",
        "id": "5f48ce592a9bb065cdf9fb33"
    },
    {
        "title": "Nagaland",
        "transform": "translate(560,240)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Nagaland",
        "text": "Nagaland",
        "id": "5f48ce592a9bb065cdf9fb35"
    },
    {
        "title": "Manipur",
        "transform": "translate(545,265)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Manipur",
        "text": "Manipur",
        "id": "5f48ce592a9bb065cdf9fb32"
    },
    {
        "title": "Mizoram",
        "transform": "translate(520,300)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Mizoram",
        "text": "Mizoram",
        "id": "5f48ce592a9bb065cdf9fb34"
    },
    {
        "title": "Ladakh",
        "transform": "translate(170,50)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Ladakh",
        "text": "Ladakh",
        "id": "5f48ce592a9bb065cdf9fb41"
    },
    {
        "title": "Arunachal Pradesh",
        "transform": "translate(570,190)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Arunachal Pradesh",
        "text": "Arunachal Pradesh",
        "id": "5f48ce592a9bb065cdf9fb21"
    },
    {
        "title": "Delhi",
        "transform": "translate(180,185)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Delhi",
        "text": "Delhi",
        "id": "5f48ce592a9bb065cdf9fb26"
    },
    {
        "title": "Telangana",
        "transform": "translate(220,420)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Telangana",
        "text": "Telangana",
        "id": "5f48ce592a9bb065cdf9fb3c"
    },
    {
        "title": "Lakshadweep",
        "transform": "translate(100,590)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Lakshadweep",
        "text": "Lakshadweep",
        "id": "5f48ce592a9bb065cdf9fb2f"
    },
    {
        "title": "Andaman and Nicobar Islands",
        "transform": "translate(520,580)",
        "fill-opacity": "0.25",
        "pointerEvents": "all",
        "fill": "none",
        "strokeWidth": "4.4",
        "radius": "5",
        "name": "Andaman and Nicobar Islands",
        "text": "Andaman and Nicobar Islands",
        "id": "5f48ce592a9bb065cdf9fb1f"
    },

] 